### ISSUE TITLE
In v13, the progress bar gets stuck during synchronization

### ISSUE THREAD

**Issue by niulinlnc** [gmarczynski/odoo-web-progress#10] opened 2019-12-24 06:30 UTC
After I used the progress bar module in the module, it is easy to get stuck and fake death when synchronizing data. If I don't use the progress bar, I can synchronize normally. I don't know why.

![进度条卡住01](https://user-images.githubusercontent.com/11767049/71399311-28b5b600-265e-11ea-8a43-e9c75c49b520.jpg)
![进度条卡住02](https://user-images.githubusercontent.com/11767049/71399316-2c493d00-265e-11ea-93e1-7521dcb44f52.jpg)
![进度条卡住03](https://user-images.githubusercontent.com/11767049/71399324-2f442d80-265e-11ea-9fd7-6a127d7a1b33.jpg)

**Comment by gmarczynski** [comment] 2019-12-24 09:04
Does it happen always or sometimes?
Does it happen only in v. 13.0?

**Comment by niulinlnc** [comment] 2019-12-25 01:11
Yes, it only happens in v13.0, and it happen always.

**Comment by MohamedAmineOuali** [comment] 2021-01-26 19:26
Hello,

I am not sure but I think that the problem is related to odoo.

In odoo 13 and 14 there is an isolation problem for transaction.

The progress bar create a new cursor (transaction) and commit the changes using the cursor.

```
        with api.Environment.manage():
            with registry(self.env.cr.dbname).cursor() as new_cr:
                # Create a new environment with new cursor database
                new_env = api.Environment(new_cr, self.env.uid, self.env.context)
                # with_env replace original env for this method
                progress_obj = self.with_env(new_env)
                for vals in vals_list:
                    progress_obj.create(vals)  # isolated transaction to commit
                # notify bus
                if notify:
                    progress_notif = progress_obj.get_progress(code)
                    new_env['bus.bus'].sendone('web_progress', progress_notif)
                new_env.cr.commit()
```

If you are doing a select and then an update (on the same record) without doing a commit. The progress bar commit will try to commit the update record and it will be blocked and hang indefinitely because of a lock on the database.   You can check this using `select * from pg_stat_activity` query for postgresql.

**Comment by gmarczynski** [comment] 2021-03-23 20:40
@niulinlnc can you please check the latest version 1.4 - I just committed fixes for two deadlock situations:
- the deletion of bus.bus records (executed randomly in  `sendone`) may have caused deadlock
- user name was retrieved on each bus.bus message in a new transaction and may have caused deadlock if the main progress operation was related to res.users

**Comment by gmarczynski** [comment] 2021-03-23 23:47
@MohamedAmineOuali Thank you. I think it is fixed now. I clear the environments' towrite/tocompute lists for the time of the progress and bus message creation and their commit and restore the lists just afterwards. My test scenario that was blocked in the previous version, moves forward now. Can you confirm?

**Comment by gmarczynski** [comment] 2021-08-21 12:03
Since there is no answer for lat 6 months I consider this issue solved.

**Closed as completed by gmarczynski** 2021-08-21 12:03 UTC
